import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#103040',
  },
  title: {
    fontSize: 34,
    color: '#fff',
    marginTop: -60,
    marginBottom: 30,
  },
  dataView: {
    width: '80%',
    borderRadius: 8,
    marginVertical: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff2',
  },
  input: {
    width: '56%',
    padding: 12,
    fontSize: 16,
    color: '#fff',
    marginLeft: 5,
    marginRight: 5,
    borderRadius: 8,
    paddingLeft: 20,
    backgroundColor: '#203040',
  },
  agePicker: {
    margin: 10,
    height: 50,
    width: 100,
    color: '#fff',
    backgroundColor: '#203040',
  },
  sexView: {
    width: '80%',
    borderRadius: 8,
    paddingLeft: 10,
    marginVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff2',
  },
  sexLabel: {
    fontSize: 20,
    color: '#e4b02b',
  },
  sexPicker: {
    margin: 10,
    height: 50,
    width: 105,
    color: '#fff',
    backgroundColor: '#203040',
  },
  sliderView: {
    width: '80%',
    borderRadius: 8,
    paddingLeft: 15,
    marginVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff2',
  },
  sliderLabel: {
    fontSize: 22,
    marginTop: -4,
    color: '#e4b02b',
    fontWeight: 'bold',
  },
  slider: {
    width: 200,
    height: 50,
  },
  priceLabel: {
    fontSize: 26,
    color: '#00FF66',
    marginTop: 5,
  },
  switchView: {
    height: 50,
    width: '70%',
    marginTop: 50,
    paddingLeft: 8,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff2',
  },
  switch: {
    marginHorizontal: 20,
  },
  studentLabel: {
    fontSize: 22,
    color: '#e4b02b',
  },
  button: {
    height: 45,
    width: '32%',
    borderRadius: 8,
    marginVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00FF99',
  },
  btnText: {
    fontSize: 17,
    color: '#7159c0',
    fontWeight: 'bold',
  },
});

export default styles;